### ISSUE TITLE
try_sync

### ISSUE THREAD

**Issue by anlumo** [Logicalshift/desync#1]
First off, thanks for this crate! It's helping me a lot cleaning up the thread synchronization in my project.

However, I'm running into deadlock problems with a Desync, where one of its Futures is blocked by an operation that has to happen on the main thread, while the main thread is blocked on a `.sync` call on the same Desync (aka deadlock).

It'd be great to have a `.try_sync` function on Desync, so I can handle these situations gracefully.

**Comment by Logicalshift** [comment]
Hi, this might be something I can take a look at, though I think I need to understand a bit more about what you're looking for. I think a `try_sync()` function might have two possible implementations:

* It only tries to evaluate its function if the queue is idle at the time it is called, and otherwise does nothing
* It only runs synchronously if the queue is able to run at the time it is called, and otherwise runs in the background

Are either of these the implementation you were looking for?

One of my goals is to keep the API as small as possible, so another question I'd have is if there was a way to fix your issue with the existing API? Given that futures are involved, can you replace the blocked `sync()` call with a `future()` call, or wrap it in a `future()` call higher up the call stack? Desync futures already work a bit like the second suggestion for a `try_sync()` call, and can be thrown away if you don't want to keep polling for the result (the payload function will get executed in any case).

Another possibility if you don't need the result of the operation straight away is to use another `Desync` to store the result, and calculate it there with a `desync()` call. It can then be retrieved via a later `sync` (or `future`) call when all of the other operations have completed.

**Comment by anlumo** [comment]
The one I need for my task is the first you listed, with the addition that the caller has to be informed whether the operation was actually executed (by a `Result` return for example), which is the same as `std::io::ErrorKind::WouldBlock` result for async I/O. Then the caller could decide on how to react to this situation.

> if there was a way to fix your issue with the existing API?

Well, yes and no. My workaround now is that I have an AtomicBool that's set to true while the operation is in progress. Then in my critical section, I `compare_and_swap` that flag to check whether the Desync is idle at the moment and only call `.sync` if it is. I'm essentially externally synchronizing the Desync, which is rather inconvenient.

In Rust, Futures always defer their calls by one poll cycle, so that's no good for me there. I'm in a render loop on the main thread (using wgpu-rs), so there's nothing asynchronous on top of this. Also, the data structures wrapped by the Desync are constantly changing (it's the list of objects currently being rendered), so there's no distinct operation that can complete with a final result.

**Comment by Logicalshift** [comment]
I've added a new v0.7.0 branch that has this type of `try_sync`, if you want to try it out and see if it helps with your situation.

**Comment by anlumo** [comment]
Sorry for the delay, I'm pretty busy with our project that uses desync! This is exactly what I was looking for.

Here is my test code:

```rust
use desync::Desync;
use futures::executor::ThreadPool;
use std::sync::Arc;

struct Foo(usize);

impl Foo {
    fn foo(&mut self) {
        self.0 += 1;
        eprintln!("Foo! [{}]", self.0);
    }
}

fn main() {
    let pool = ThreadPool::new().unwrap();
    let foo = Arc::new(Desync::new(Foo(0)));

    for _ in 0..100 {
        let inner_foo = foo.clone();
        pool.spawn_ok(async move {
            let result = inner_foo.try_sync(|foo| {
                foo.foo();
            });
            if result.is_err() {
                eprintln!("Failed.");
            }
        });
    }
    eprintln!("Done.");
}
```
